version: '2'
services:
    redis:
        image: redis
    app:
        build: .
        command: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
        environment:
          - REDIS_HOST=redis
        depends_on:
          - redis
