version: "3"
services:
    redis:
        image: redis
    postgres:
        image: postgres
        environment:
          - POSTGRES_DB=chat
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=ninjas
    app:
        build: .
        command: sh -c "sleep 10 && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
        environment:
          - DJANGO_DEBUG=True
          - DJANGO_LOG_LEVEL=INFO
          - REDIS_HOST=redis
          - POSTGRES_HOST=postgres
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=ninjas
        depends_on:
          - redis
          - postgres
